### ISSUE TITLE
Nuget packages in project.json not supported

### ISSUE THREAD

**Issue by damianon** [Azure/Azure-Functions#553]
Hello, I'm using VS Code and the node func cli to develop some functions. As such they use the function.json/run.csx structure. In the project there are multiple functions, but for one function I added a project.json file for nuget dependencies as stated in the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages). So nuget doesn't seem to support project.json, but there are no examples for csproj and I'm not sure if Azure even supports those.

What is the correct solution to this issue? Using an older nuget version? Or maybe Azure does support csproj and the documentation is just not updated?

For reference I added my code below.

```
[18.10.2017 08:42:58] Package references have been updated.
[18.10.2017 08:42:58] Restoring packages.
[18.10.2017 08:42:58] Starting NuGet restore
[18.10.2017 08:42:59] Invalid input 'project.json'. Provide the path of an msbuild solution file instead. Support for XProj and standalone project.json fi
les has been removed, to continue working with legacy projects use NuGet 3.5.x from https://nuget.org/downloads
[18.10.2017 08:42:59]
[18.10.2017 08:42:59]
[18.10.2017 08:42:59] Packages restored.
[18.10.2017 08:42:59] run.csx(5,7): error CS0246: The type or namespace name 'SendGrid' could not be found (are you missing a using directive or an assemb
ly reference?)
```

My project.json

```
{
	"frameworks": {
		"net46": {
			"dependencies": {
				"Sendgrid": "9.9.0",
				"Microsoft.Azure.WebJobs.Extensions.SendGrid": "2.0.0"
			}
		}
	}
}
```

and run.csx

```
#r "Microsoft.WindowsAzure.Storage"
#load "../Common/Dto/Order.csx"

using Microsoft.WindowsAzure.Storage.Table;
using Sendgrid.Helpers.Mail;

public static void Run(string blob,Order order, string name, TraceWriter log)
{
    log.Info($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {blob.Length} Bytes");
    log.Info($"{order.Email}");
}
```

**Comment by pragnagopa** [comment]
If you are using functions v2, please use extensions.csproj https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages. If this is still an issue with functions v1, please reopen.
